---
# This is a yaml file that contains the PERTURBO workflow information.
# It is used to generate the interactive workflow.

DFT:
 non-interactive: True

DFPT:
 non-interactive: True

qe2pert:
 computes: E-ph matrix elements on the coarse $$\mathbf{k}$$ point (determined by the nscf step) and $$\mathbf{q}$$ point (determined by the phonon step) Brillouin zone grids as well as in the Wannier basis.
 parents:
   - DFT
   - DFPT
 requirements:
   - phdir
   - prefix_centres.xyz
   - prefix_u.mat
   - prefix_u_dis.mat
 outputs:
   - prefix_epwan.h5

bands:
 parents:
   - qe2pert
 computes: Interpolated electronic band structure given an electronic crystal momentum path.
 requirements:
    - prefix_epwan.h5
    - prefix_band.kpt
 outputs:
    - prefix.bands

phdisp:
 parents:
   - qe2pert
 computes: Interpolated phonon dispersions along a given crystal momentum path.
 requirements:
    - prefix_epwan.h5
    - prefix_phdisp.qpt
 outputs:
    - prefix.phdisp

ephmat:
 parents:
   - qe2pert
 computes: The absolute values of the e-ph matrix elements, summed over the number of electronic bands, given two lists of $$\mathbf{k}$$ and $$\mathbf{q}$$ points. In a typical scenario, one computes the e-ph matrix elements for a chosen $$\mathbf{k}$$ point as a function of $$\mathbf{q}$$ point.
 requirements:
    - prefix_epwan.h5
    - prefix_band.kpt
    - prefix_phdisp.qpt
 outputs:
    - prefix.ephmat

imsigma:
 parents:
   - qe2pert
 optional parents:
   - setup
 computes: The imaginary part of the lowest-order (so-called 'Fan') e-ph self-energy, $$\operatorname{Im}\Sigma$$, for states in a range of bands and with crystal momenta $$\mathbf{k}$$ read from a list (this list can be obtained from <code>calc_mode='setup'</code> or created manually). The scattering rates can also be obtained using $${2} \operatorname{Im}\Sigma /{\hbar}$$.
 requirements:
    - prefix_epwan.h5
    - prefix_tet.kpt
    - prefix.temper
 outputs:
    - prefix.imsigma
    - prefix.imsigma_mode

setup:
 parents:
   - qe2pert
 computes: Set up transport property calculations (i.e., electrical conductivity, carrier mobility and Seebeck) by providing $$\mathbf{k}$$ points, $$\mathbf{k}$$ point tetrahedra and (if needed) finding chemical potentials for given carrier concentrations.
 requirements:
    - prefix_epwan.h5
    - prefix.temper
 outputs:
    - prefix.doping
    - prefix_tet.h5
    - prefix_tet.kpt
    - prefix.dos

meanfp:
 parents:
   - imsigma
 computes: The e-ph mean free paths for electronic states in a user-defined $$\mathbf{k}$$ point list and range of bands.
 requirements:
    - prefix_epwan.h5
    - prefix_tet.kpt
    - prefix.temper
    - prefix.imsigma
 outputs:
    - prefix.mfp
    - prefix.vel

trans:
 parents:
   - setup
 optional parents:
   - imsigma
 computes: The phonon-limited conductivity and carrier mobility.
 requirements:
    - prefix_epwan.h5
    - prefix.temper
    - prefix_tet.h5
 optional files:
    - prefix.imsigma
 outputs:
    - prefix.cond
    - prefix.tdf
    - prefix_tdf.h5

trans-pp:
 parents:
   - trans
 computes: Seebeck coefficient. Note that phonon drag effects are not included in this calculation.
 requirements:
    - prefix_epwan.h5
    - prefix.temper
    - prefix_tet.h5
    - prefix_tdf.h5
 outputs:
    - prefix.trans_coef

dynamics-run:
 parents:
   - setup
 computes: "Ultrafast hot carrier dynamics via the time-dependent Boltzmann transport equation: set an initial carrier distribution and calculate its evolution in time."
 requirements:
   - prefix.temper
   - prefix_tet.h5
 outputs:
   - prefix_cdyna.h5

dynamics-pp:
 parents:
   - dynamics-run
 computes: "Postprocessing of the ultrafast dynamics calculations: carrier population as a function of energy and time."
 requirements:
   - prefix_cdyna.h5
 outputs:
   - prefix_cdyna.dat
   - prefix_popu.h5
...
